config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        confirmations: 'users/confirmations'
      } 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  # resources 'employees' do
  #   collection do
  #     post :new
  #   end
  # end

  resources :employees;

  resources :documents
  
  # get 'employees/new'

  #public pages routes / custom routes
  get 'about' => 'pages#about_us'
  get 'contact-us' => 'pages#contact_us'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-and-conditions' => 'pages#terms_and_conditions'
end

app/models/employee.rb
class Employee < ApplicationRecord

    has_many :documents

    validates :first_name, :last_name, presence: true
    validates :personal_email, presence: true, uniqueness: true
    validates :city, :state, :pincode, :address_line_1, presence: true

    def name
        "#{first_name} #{middle_name} #{last_name}".strip
    end

    def full_address
        "#{address_line_1} #{city}, #{state}, #{country}, #{pincode}".strip
    end
    
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :set_employee, only: [:edit, :update, :show, :destroy]

    def index
        @employees = Employee.all
    end

    def new 
        @employee = Employee.new
    end

    def create
        # @employee = Employee.new(first_name: params[:employee][:first_name],
        # middle_name_name: params[:employee][:middle_name_name],
        # last_name: params[:employee][:last_name],
        # personal_email: params[:employee][:personal_email],
        # address_line_1: params[:employee][:address_line_1],
        # address_line_2: params[:employee][:address_line_2],
        # city: params[:employee][:city],
        # state: params[:employee][:state],
        # country: params[:employee][:country],
        # pincode: params[:employee][:pincode])

        @employee = Employee.new(employee_params)
        if @employee.save
            redirect_to employees_path, notice: 'Employees has been created successfully.'
        else
            render :new
        end
    end

    def edit
    end

    def update
        if(@employee.update(employee_params))
            redirect_to employees_path, notice: 'Employees has been updated successfully'
        else
            render :edit
        end
    end

    def show
    end

    def destroy
        if @employee.destroy
            redirect_to employees_path, notice: 'Employee has been deleted successfully'
        else
            render :new
        end
    end

    private
    def employee_params
        params.require(:employee).permit(:first_name, :middle_name, :last_name, :personal_email, :address_line_1, :address_line_2, :city, :state, :country, :pincode)
    end

    def set_employee
        @employee = Employee.find(params[:id])
    end

end

app/views/employees/_form.html.erb
<%= form_with model: employee do |form| %>
    
    <% if @employee.errors.any? %>
        <div>
                <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this post from being saved:</h2>
                <ul>
                <% @employee.errors.each do |error| %>
                    <li><%= error %></li>
                <% end %>
                </ul>
        </div>
    <% end %>

        <p class="">Those fields are mandatory which has * symbol.</p>
        <div class="row">
            <div class="col-lg-4">
                <div class="form-group">
                    <span><%= form.label :first_name, class: 'mb-2' %>*</span>
                    <%= form.text_field :first_name, class: 'form-control form-control-lg rounded-0' %>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :middle_name, class: 'mb-2' %>
                    <%= form.text_field :middle_name, class: 'form-control form-control-lg rounded-0' %>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="form-group">
                    <span><%= form.label :last_name, class: 'mb-2' %>*</span>
                    <%= form.text_field :last_name, class: 'form-control form-control-lg rounded-0' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4">
                <div class="form-group">
                    <span><%= form.label :personal_email, class: 'mb-2' %>*</span>
                    <%= form.text_field :personal_email, class: 'form-control form-control-lg rounded-0' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <span><%= form.label :address_line_1, class: 'mb-2' %>*</span>
                    <%= form.text_field :address_line_1, class: 'form-control form-control-lg rounded-0' %>
                </div>
            </div>

            <div class="col-lg-6">
                <div class="form-group">
                    <%= form.label :address_line_2, class: 'mb-2' %>
                    <%= form.text_field :address_line_2, class: 'form-control form-control-lg rounded-0' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <span><%= form.label :city, class: 'mb-2' %>*</span>
                    <%= form.text_field :city, class: 'form-control form-control-lg rounded-0' %>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <span><%= form.label :state, class: 'mb-2' %>*</span>
                    <%= form.text_field :state, class: 'form-control form-control-lg rounded-0' %>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <span><%= form.label :country, class: 'mb-2' %>*</span>
                    <%= form.text_field :country, class: 'form-control form-control-lg rounded-0' %>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <span><%= form.label :pincode, class: 'mb-2' %>*</span>
                    <%= form.text_field :pincode, class: 'form-control form-control-lg rounded-0' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 mt-4">
                <%= form.submit class: 'btn btn-primary btn-lg rounded-0' %>
                <%= link_to 'Back to Employees', employees_path, class: 'btn btn-outline-primary btn-lg rounded-0' %>
            </div>
        </div>
        
    <% end %>

app/views/employees/document.html.erb
<h1>Documents</h1>

app/views/employees/edit.html.erb
<div class="col-lg-12" >
    <div class="card rounded-0  mt-4 mb-4" style="background:linear-gradient(white,skyblue,white)">
        <div class="card-body">
            <h2 class="text-center">Edit Employee</h2>
        </div>
    </div>

    <%= render 'form', employee: @employee %>
</div>

app/views/employees/index.html.erb
<div class="col-lg-12">
<%#= flash :notice %>
<div class="card  mb-5 rounded-0" style="background:linear-gradient(white,skyblue,white)">
    <div class="card-body">
        <h2 class="text-center" style="">Listing Employee</h2>
        <%#<marquee direction="right" behavior="scroll" scrollamount="5"></marquee>%>
    </div>
</div>

<%= link_to 'Create New Employee', new_employee_path, class: 'btn btn-primary btn-lg mb-4 rounded-0', style: 'text-decoration: none;' %>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Address</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @employees.each do |employee| %>
            <tr>
                <td class="col-2"><%= employee.name %></td>
                <td class="col-2"><%= employee.personal_email %></td>
                <td class="col-4"><%= employee.full_address %></td>
                <td>

                    <!--    <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Actions
                        </button>
                        <ul class="dropdown-menu">
                            <li><%#= link_to 'Edit', edit_employee_path(employee), class: 'dropdown-item' %></li>
                            <li><%#= link_to 'View', employee_path(employee), class: 'dropdown-item' %></li>
                            <li><%#= link_to 'Delete', employee_path(employee), class: 'dropdown-item', method: :delete, data: { confirm: 'Are you sure to delete this employee?'} %></li>
                        </ul>
                    </div>-->
                    
                    <%= link_to 'Edit', edit_employee_path(employee), class: 'btn btn-primary' %>
                    <%= link_to 'View', employee_path(employee), class: 'btn btn-info' %>
                    <%= link_to 'Delete', employee_path(employee), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure to delete this employee?'} %>
                    <%= link_to 'Documents', employee_path(employee), class: 'btn btn-info' %>
                    
                </td>
            </tr>
        
        <% end %>
    </tbody>

</table>
</div >

app/views/employees/new.html.erb
<div class="col-lg-12" >
    <div class="card rounded-0  mt-4 mb-4" style="background:linear-gradient(white,skyblue,white)">
        <div class="card-body">
            <h2 class="text-center">Create New Employee</h2>
        </div>
    </div>

    <%= render 'form', employee: @employee %>
</div>

app/views/employees/show.html.erb
<div class="col-lg-12" >
    <div class="card rounded-0  mt-4 mb-4" style="background:linear-gradient(white,skyblue,white)">
        <div class="card-body">
            <h2 class="text-center">Employee Details</h2>
        </div>
    </div>

        <div class="row m-1"  style="background:linear-gradient(white,skyblue,white)">
            <div class="col-lg-6 mt-2 rounded-0">
                <div class="">
                    <h3 class="mb-3">Personal Information</h3>
                    <p class="lead"><strong>First Name: </strong><%=@employee.first_name %></p>
                    <p class="lead"><strong>Middle Name: </strong><%=@employee.middle_name%></p>
                    <p class="lead"><strong>last Name: </strong><%=@employee.last_name %></p>
                    <p class="lead"><strong>Personal Email: </strong><%=@employee.personal_email %></p>
                </div>
            </div>

            <div class="col-lg-6  mt-2 rounded-0">
                <div class="">
                    <h3 class="mb-3">Address Information</h3>
                    <p class="lead"><strong>Address Line 1: </strong><%=@employee.address_line_1 %></p>
                    <p class="lead"><strong>Address Line 2: </strong><%=@employee.address_line_2 %></p>
                    <p class="lead"><strong>City: </strong><%=@employee.city %></p>
                    <p class="lead"><strong>State: </strong><%=@employee.state %></p>
                    <p class="lead"><strong>Country: </strong><%=@employee.country %></p>
                    <p class="lead"><strong>Pincode: </strong><%=@employee.pincode %></p>
                </div>
            </div>
        </div>
            <%= link_to 'Back to Employees', employees_path, class: 'btn btn-outline-primary btn-lg rounded-0 mt-2' %>
            <%= link_to 'Edit Employees', edit_employee_path, class: 'btn btn-primary btn-lg rounded-0 mt-2' %>
    
</div>