config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        confirmations: 'users/confirmations'
      } 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  # resources 'employees' do
  #   collection do
  #     post :new
  #   end
  # end

  resources :employees;

  resources :documents
  
  # get 'employees/new'

  #public pages routes / custom routes
  get 'about' => 'pages#about_us'
  get 'contact-us' => 'pages#contact_us'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-and-conditions' => 'pages#terms_and_conditions'
end

app/views/shared/_dummy_content.html.erb
    <p class="lead">It is a long established fact that a reader will be distracted by the readable     content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a   more-or-less normal distribution of letters, as opposed to using 'Content here, content here',    making it look like readable English. Many desktop publishing packages and web page editors now    use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many  web sites still in their infancy. Various versions have evolved over the years, sometimes by     accident, sometimes on purpose (injected humour and the like).</p>

    <p class="lead">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
    
    <p class="lead">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>

app/views/shared/_footer.html.erb
<div class="b-example-divider"></div>

<div class="container">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item">
                <%= link_to 'Home', root_path, class: 'nav-link px-2 text-muted' %>
                <!--<a href="#" class="nav-link px-2 text-muted">Home</a>-->
            </li>
            <li class="nav-item">
                <%= link_to 'About Us', about_path, class: 'nav-link px-2 text-muted' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Contact Us', contact_us_path, class: 'nav-link px-2 text-muted' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Privacy Policy', privacy_policy_path, class: 'nav-link px-2 text-muted' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Terms and Conditions', terms_and_conditions_path, class: 'nav-link px-2 text-muted' %>
            </li>

            <!--<li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>-->
        </ul>
        <p class="text-center text-muted">&copy; 2021 Company, Inc</p>
    </footer>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to 'HR-Mitra', root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Settings
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="javascript:void(0)">Signed in as <%= current_user.email %></a></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, class: 'dropdown-item', method: :delete, data: { confirm: 'If you logout, your current session will be destroyed. Are you sure you want to logout?' } %></li>
            <!--<li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
          </ul>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: 'nav-link active' %>
          </li>
        <% end %>
        <!--<li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>-->
      </ul>
      <!--<form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>-->
    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<h1>HR-Mitra</h1>
<%= link_to 'About Us', about_path, data: {name: 'about-page', resource: 'pages'}, style: 'color:green' %>
<%= link_to 'Contact Us', contact_us_path, data: {name: 'about-page', resource: 'pages'}, style: 'color:green' %>
<%= link_to 'Privacy Policy', privacy_policy_path, data: {name: 'about-page', resource: 'pages'}, style: 'color:green' %>
<%= link_to 'Terms and Conditions', terms_and_conditions_path, data: {name: 'about-page', resource: 'pages'}, style: 'color:green' %>